name: Build multiple versions and push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.name 'Boyt'
          git config --global user.email '5825564-HARDY8118@users.noreply.gitlab.com'
          git config --global pull.rebase false
      - name: Fetch release branch from origin
        run: git fetch origin release
      - name: Change to release branch
        run: git checkout -b release
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Delete build directory
        run: rm -r build/
      - name: Make build directory
        run: mkdir -p build
      - name: Build binaries
        run: ./build.sh
        shell: bash
      - name: Add built files
        run: git add build
      - name: Check status
        run: git status
      - name: Commit built files
        run: git commit -m "Build"
      - name: Push to origin
        run: git push origin release_$(date +%Y-%m-%d-%H-%M)
