name: Deploy multiple versions and push
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                token: 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
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'
            - name: Make directory
              run: mkdir build
            - name: Build
              run: ./build.sh
              shell: bash
            - name: Configure git
              run: |
                git config --global user.name 'Boyt'
                git config --global user.email '5825564-HARDY8118@users.noreply.gitlab.com'
            - name: Add files
              run: git add build
            - name: Commit
              run: git commit -m "Build"
            - name: Push
              run: git push
            